"""Create owner-scoped GitHub installations and repository review settings."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installations",
        sa.Column("installation_id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "installation_id ~ '^[1-9][0-9]{0,31}$'",
            name=op.f("ck_github_installations_installation_id_decimal"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_github_installations_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("installation_id", name=op.f("pk_github_installations")),
        sa.UniqueConstraint("installation_id", "owner_id", name="uq_installation_owner"),
    )
    op.create_index(
        op.f("ix_github_installations_owner_id"), "github_installations", ["owner_id"], unique=False
    )
    op.create_table(
        "review_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("installation_id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.String(length=32), nullable=False),
        sa.Column("repo_name", sa.String(length=201), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("min_pr_lines", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "skip_paths",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "focus",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'["security","performance","quality"]\'::jsonb'),
            nullable=False,
        ),
        sa.Column("rules_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(skip_paths) = 'array' AND jsonb_array_length(skip_paths) <= 100",
            name=op.f("ck_review_settings_skip_paths_bounded"),
        ),
        sa.CheckConstraint(
            "repo_id ~ '^[1-9][0-9]{0,31}$'", name=op.f("ck_review_settings_repo_id_decimal")
        ),
        sa.CheckConstraint(
            'jsonb_typeof(focus) = \'array\' AND jsonb_array_length(focus) BETWEEN 1 AND 3 AND focus <@ \'["security","performance","quality"]\'::jsonb',
            name=op.f("ck_review_settings_focus_valid"),
        ),
        sa.CheckConstraint(
            "min_pr_lines > 0", name=op.f("ck_review_settings_min_pr_lines_positive")
        ),
        sa.CheckConstraint(
            "rules_version > 0", name=op.f("ck_review_settings_rules_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["installation_id", "owner_id"],
            ["github_installations.installation_id", "github_installations.owner_id"],
            name="fk_review_settings_installation_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_settings")),
        sa.UniqueConstraint(
            "installation_id", "repo_id", name="uq_review_settings_installation_repo"
        ),
    )
    op.create_index(
        op.f("ix_review_settings_owner_id"), "review_settings", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_settings_owner_id"), table_name="review_settings")
    op.drop_table("review_settings")
    op.drop_index(op.f("ix_github_installations_owner_id"), table_name="github_installations")
    op.drop_table("github_installations")
    # ### end Alembic commands ###
