"""Persist review jobs, delivery inbox, lease-fenced attempts and outbox intent."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("installation_id", sa.String(length=32), nullable=False),
        sa.Column("repo_id", sa.String(length=32), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column("rules_version", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "analysis_status",
            sa.String(length=16),
            server_default=sa.text("'queued'"),
            nullable=False,
        ),
        sa.Column(
            "publication_status",
            sa.String(length=24),
            server_default=sa.text("'not_requested'"),
            nullable=False,
        ),
        sa.Column(
            "publication",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'{"status":"not_requested"}\'::jsonb'),
            nullable=False,
        ),
        sa.Column(
            "findings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("dispatch_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "analysis_status IN ('draft','queued','processing','analyzed','partial','failed','skipped','superseded','cancelled')",
            name=op.f("ck_review_jobs_analysis_status_valid"),
        ),
        sa.CheckConstraint(
            "head_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'", name=op.f("ck_review_jobs_head_sha_valid")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(findings) = 'array'", name=op.f("ck_review_jobs_findings_array")
        ),
        sa.CheckConstraint("provider = 'anthropic'", name=op.f("ck_review_jobs_provider_valid")),
        sa.CheckConstraint(
            "publication_status IN ('not_requested','preview_ready','publishing','published','partially_published','publish_unknown','failed','blocked')",
            name=op.f("ck_review_jobs_publication_status_valid"),
        ),
        sa.CheckConstraint(
            "repo_id ~ '^[1-9][0-9]{0,31}$'", name=op.f("ck_review_jobs_repo_id_decimal")
        ),
        sa.CheckConstraint(
            "max_attempts > 0 AND dispatch_version > 0", name=op.f("ck_review_jobs_limits_positive")
        ),
        sa.CheckConstraint(
            "pr_number > 0 AND rules_version > 0", name=op.f("ck_review_jobs_identity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["installation_id", "owner_id"],
            ["github_installations.installation_id", "github_installations.owner_id"],
            name="fk_review_jobs_installation_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_jobs")),
        sa.UniqueConstraint("id", "owner_id", name="uq_review_jobs_id_owner"),
        sa.UniqueConstraint(
            "owner_id",
            "installation_id",
            "repo_id",
            "pr_number",
            "head_sha",
            "rules_version",
            "provider",
            name="uq_review_jobs_identity",
        ),
    )
    op.create_index(op.f("ix_review_jobs_owner_id"), "review_jobs", ["owner_id"], unique=False)
    op.create_table(
        "review_attempts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "kind IN ('analysis','publication')", name=op.f("ck_review_attempts_kind_valid")
        ),
        sa.CheckConstraint(
            "status IN ('running','succeeded','failed','abandoned','unknown')",
            name=op.f("ck_review_attempts_status_valid"),
        ),
        sa.CheckConstraint("lease_until > started_at", name=op.f("ck_review_attempts_lease_valid")),
        sa.CheckConstraint("number > 0", name=op.f("ck_review_attempts_number_positive")),
        sa.ForeignKeyConstraint(
            ["job_id", "owner_id"],
            ["review_jobs.id", "review_jobs.owner_id"],
            name=op.f("fk_review_attempts_job_id_review_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_attempts")),
        sa.UniqueConstraint("job_id", "kind", "number", name="uq_review_attempt_number"),
    )
    op.create_index(op.f("ix_review_attempts_job_id"), "review_attempts", ["job_id"], unique=False)
    op.create_table(
        "review_deliveries",
        sa.Column("delivery_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('opened','synchronize')", name=op.f("ck_review_deliveries_action_valid")
        ),
        sa.CheckConstraint(
            "event_type = 'pull_request'", name=op.f("ck_review_deliveries_event_valid")
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "owner_id"],
            ["review_jobs.id", "review_jobs.owner_id"],
            name=op.f("fk_review_deliveries_job_id_review_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("delivery_id", name=op.f("pk_review_deliveries")),
    )
    op.create_index(
        op.f("ix_review_deliveries_job_id"), "review_deliveries", ["job_id"], unique=False
    )
    op.create_table(
        "review_outbox",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('analyze','reconcile_publication')", name=op.f("ck_review_outbox_kind_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending','dispatched','cancelled')",
            name=op.f("ck_review_outbox_status_valid"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_review_outbox_version_positive")),
        sa.ForeignKeyConstraint(
            ["job_id", "owner_id"],
            ["review_jobs.id", "review_jobs.owner_id"],
            name=op.f("fk_review_outbox_job_id_review_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_outbox")),
        sa.UniqueConstraint("job_id", "version", name="uq_review_outbox_job_version"),
    )
    op.create_index(op.f("ix_review_outbox_job_id"), "review_outbox", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_outbox_job_id"), table_name="review_outbox")
    op.drop_table("review_outbox")
    op.drop_index(op.f("ix_review_deliveries_job_id"), table_name="review_deliveries")
    op.drop_table("review_deliveries")
    op.drop_index(op.f("ix_review_attempts_job_id"), table_name="review_attempts")
    op.drop_table("review_attempts")
    op.drop_index(op.f("ix_review_jobs_owner_id"), table_name="review_jobs")
    op.drop_table("review_jobs")
    # ### end Alembic commands ###
