"""Encrypted Run snapshots and node lifecycle records."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0023"
down_revision = "0022"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_version", sa.Integer(), nullable=False),
        sa.Column("snapshot_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column(
            "state", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("token_limit", sa.Integer(), nullable=False),
        sa.Column("cost_limit", sa.Integer(), nullable=False),
        sa.Column("charged_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("charged_cost", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reserved_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reserved_cost", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("checkpoint_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(state IN ('pending','running') AND finished_at IS NULL) OR (state NOT IN ('pending','running') AND finished_at IS NOT NULL)",
            name=op.f("ck_agent_runs_terminal_time"),
        ),
        sa.CheckConstraint(
            "checkpoint_version >= 0 AND jsonb_typeof(checkpoint) = 'object' AND octet_length(checkpoint::text) <= 4096",
            name=op.f("ck_agent_runs_checkpoint_bounds"),
        ),
        sa.CheckConstraint(
            "state IN ('pending','running','succeeded','partial','failed','cancelled')",
            name=op.f("ck_agent_runs_valid_state"),
        ),
        sa.CheckConstraint(
            "charged_tokens >= 0 AND reserved_tokens >= 0 AND charged_tokens + reserved_tokens <= token_limit AND charged_cost >= 0 AND reserved_cost >= 0 AND charged_cost + reserved_cost <= cost_limit",
            name=op.f("ck_agent_runs_budget_usage"),
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_agent_runs_retention")),
        sa.CheckConstraint(
            "octet_length(snapshot_ciphertext) BETWEEN 1 AND 4000000",
            name=op.f("ck_agent_runs_snapshot_size"),
        ),
        sa.CheckConstraint(
            "token_limit BETWEEN 1 AND 32000 AND cost_limit BETWEEN 1 AND 1000000",
            name=op.f("ck_agent_runs_budget_limits"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "workflow_version"],
            ["workflow_revisions.workflow_id", "workflow_revisions.version"],
            name=op.f("fk_agent_runs_workflow_id_workflow_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(op.f("ix_agent_runs_expires_at"), "agent_runs", ["expires_at"], unique=False)
    op.create_index(op.f("ix_agent_runs_user_id"), "agent_runs", ["user_id"], unique=False)
    op.create_table(
        "agent_run_nodes",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column(
            "state", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("input_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("output_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("retries", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("usage_uncertain", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("reserved_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reserved_cost", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(state IN ('pending','running') AND finished_at IS NULL) OR (state NOT IN ('pending','running') AND finished_at IS NOT NULL)",
            name=op.f("ck_agent_run_nodes_terminal_time"),
        ),
        sa.CheckConstraint(
            "error_code IS NULL OR error_code IN ('missing_key','invalid_key','unsupported_model','budget_exceeded','provider_timeout','provider_rate_limit','provider_unavailable','provider_auth','provider_invalid','unsafe_output','tool_failed','tool_limit','cancelled','dependency_failed','internal_error')",
            name=op.f("ck_agent_run_nodes_error_code"),
        ),
        sa.CheckConstraint(
            "state IN ('pending','running','succeeded','failed','skipped','cancelled')",
            name=op.f("ck_agent_run_nodes_valid_state"),
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 9 AND retries BETWEEN 0 AND 2",
            name=op.f("ck_agent_run_nodes_attempt_bounds"),
        ),
        sa.CheckConstraint(
            "input_ciphertext IS NULL OR octet_length(input_ciphertext) <= 500000",
            name=op.f("ck_agent_run_nodes_input_size"),
        ),
        sa.CheckConstraint(
            "output_ciphertext IS NULL OR octet_length(output_ciphertext) <= 200000",
            name=op.f("ck_agent_run_nodes_output_size"),
        ),
        sa.CheckConstraint(
            "reserved_tokens >= 0 AND reserved_cost >= 0",
            name=op.f("ck_agent_run_nodes_reservation_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_run_nodes_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", "node_id", name=op.f("pk_agent_run_nodes")),
    )
    # ### end Alembic commands ###
    op.execute("""
        CREATE FUNCTION protect_agent_run() RETURNS trigger AS $$
        BEGIN
          IF (NEW.id,NEW.user_id,NEW.workflow_id,NEW.workflow_version,NEW.snapshot_ciphertext,NEW.token_limit,NEW.cost_limit,NEW.created_at,NEW.expires_at)
             IS DISTINCT FROM (OLD.id,OLD.user_id,OLD.workflow_id,OLD.workflow_version,OLD.snapshot_ciphertext,OLD.token_limit,OLD.cost_limit,OLD.created_at,OLD.expires_at)
          THEN RAISE EXCEPTION 'Run snapshot is immutable'; END IF;
          IF OLD.state IN ('succeeded','partial','failed','cancelled') THEN RAISE EXCEPTION 'Run is terminal'; END IF;
          IF NEW.state <> OLD.state AND NOT (
            (OLD.state='pending' AND NEW.state IN ('running','cancelled')) OR
            (OLD.state='running' AND NEW.state IN ('succeeded','partial','failed','cancelled'))
          ) THEN RAISE EXCEPTION 'Invalid Run transition'; END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql
    """)
    op.execute(
        "CREATE TRIGGER agent_run_protected BEFORE UPDATE ON agent_runs FOR EACH ROW EXECUTE FUNCTION protect_agent_run()"
    )
    op.execute("""
        CREATE FUNCTION protect_agent_run_node() RETURNS trigger AS $$
        BEGIN
          IF (NEW.run_id,NEW.node_id) IS DISTINCT FROM (OLD.run_id,OLD.node_id)
          THEN RAISE EXCEPTION 'Node identity is immutable'; END IF;
          IF OLD.state IN ('succeeded','failed','skipped','cancelled') THEN RAISE EXCEPTION 'Node is terminal'; END IF;
          IF OLD.input_ciphertext IS NOT NULL AND NEW.input_ciphertext IS DISTINCT FROM OLD.input_ciphertext
          THEN RAISE EXCEPTION 'Node input is immutable'; END IF;
          IF NEW.state <> OLD.state AND NOT (
            (OLD.state='pending' AND NEW.state IN ('running','skipped','cancelled')) OR
            (OLD.state='running' AND NEW.state IN ('succeeded','failed','cancelled'))
          ) THEN RAISE EXCEPTION 'Invalid Node transition'; END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql
    """)
    op.execute(
        "CREATE TRIGGER agent_run_node_protected BEFORE UPDATE ON agent_run_nodes FOR EACH ROW EXECUTE FUNCTION protect_agent_run_node()"
    )


def downgrade() -> None:
    op.drop_table("agent_run_nodes")
    op.drop_table("agent_runs")
    op.execute("DROP FUNCTION protect_agent_run_node()")
    op.execute("DROP FUNCTION protect_agent_run()")
